meta_product_name: "Shopwise"
 meta_title: "Shopwise - Shop smarter"
 meta_description: "Price comparison, and recipe recommendation"
#  meta_image: "cover.png" # should exist in `app/assets/images/`
